using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace projecteuler
{
    internal class Program
    {
        static void Main(string[] args)
        {
            /*
              Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
              1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

              By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
            */

            //Solution
            int number1 = 0;
            int number2 = 1;
            int number3 = 0;

            int sum = 0;

            for (int i = 0; true; i++)
            {

                number3 = number1 + number2;

                if (number3 % 2 == 0)
                {

                    sum += number3;
                    if (sum > 4000000)
                    {
                        break;
                    }
                };

                Console.WriteLine(number3);
                number1 = number2;
                number2 = number3;


            }


            Console.WriteLine("Final sum: " + sum); 


            Console.ReadLine();





        }
    }
}
